name: Run Postman Collection with Newman

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-newman:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Or any version compatible with Newman

      # Install Newman globally
      - name: Install Newman
        run: npm install -g newman

      # Run the Postman collection
      - name: Run Postman collection
        run: |
          newman run poke.json \
          --reporters cli,json \
          --reporter-json-export newman-report.json
